
import torch
import os

# --- Device Configuration ---
DEVICE = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {DEVICE}")

# --- Model Configuration ---
# IMPORTANT: Update this path to your local Gemma 3 model directory.
GEMMA_MODEL_PATH = "./gemma-3-4b-it"


# --- Video Processing Configuration ---
KEYFRAME_EXTRACTION_INTERVAL = 2  # seconds - Changed from 1 to 2 to reduce frame processing
SIMILARITY_THRESHOLD = 0.85  # For ad matching

# --- Directory Configuration ---
# Base directory for all data generated by the application
BASE_DATA_DIR = "./data"

# Ensure base data directory exists
os.makedirs(BASE_DATA_DIR, exist_ok=True)

# Derived directories
DATABASE_DIR = os.path.join(BASE_DATA_DIR, "database")
MATERIALS_DIR = os.path.join(BASE_DATA_DIR, "materials")
RECORDED_VIDEOS_DIR = os.path.join(BASE_DATA_DIR, "recorded_videos")
REPORTS_DIR = os.path.join(BASE_DATA_DIR, "reports")
SCREENSHOTS_DIR = os.path.join(REPORTS_DIR, "screenshots")

# --- Database Configuration ---
DATABASE_FILE = os.path.join(DATABASE_DIR, "metadata.db")

# --- Reporter Configuration ---
NUM_SCREENSHOTS = 3
